### PR TITLE
fix: storing icon cache in `globalState` db and fix slow startup

### LINKED ISSUE #48: Storing cache in globalState is causing slow startup
### Describe the bug

We're storing icon cache in `globalState`, and it will be saved to `globalStorage/state.vscdb` which gets loaded in every startup even after uninstall

I discovered this when trying to troubleshoot why my vscode is starting slowly recently, and found something related in loading storage in `perfview.show`, and saw this big cache entry in it, removing it solves the problem

### Reproduction

Try use some icons and use `perfview.show` to see `code/didInitStorage`'s delta time

### System Info

```Shell
* Code: 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06)
* OS: win32(10.0.19045)
* CPUs: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz(12 x 2592)
* Memory(System): 15.83 GB(6.97GB free)

- 1TB M.2 SSD
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Legend-Master**
fixes #48

### CODE REVIEW

File: src/loader.ts [hunk 1]
```diff
@@ -18,20 +19,60 @@ export function UniqPromise<T>(fn: (ctx: ExtensionContext, id: string) => Promis
...
+}
+
+function migrateCache(ctx: ExtensionContext) {
+  const prefix = 'icons-'
+  for (const key of ctx.globalState.keys()) {
+    if (key.startsWith(prefix)) {
+      const cached = ctx.globalState.get<IconifyJSON>(key)!
+      const iconSetId = key.slice(prefix.length)
+      LoadedIconSets[iconSetId] = cached
+      writeCache(ctx, iconSetId, cached)
```
Comment (antfu) [inline src/loader.ts:62]:
```suggestion
      await writeCache(ctx, iconSetId, cached)
```

File: src/loader.ts [hunk 2]
```diff
@@ -42,8 +83,8 @@ export const LoadIconSet = UniqPromise(async (ctx: ExtensionContext, id: string)
         Log.info(`☁️ [${id}] Downloading from ${url}`)
         data = await $fetch(url)
         Log.info(`✅ [${id}] Downloaded`)
-        ctx.globalState.update(key, data)
-        LoadedIconSets[id] = data!
+        writeCache(ctx, id, data)
```
Comment (antfu) [inline src/loader.ts:86]:
```suggestion
        await writeCache(ctx, id, data)
```

Comment (Legend-Master) [reply src/loader.ts:86]: I don't think we should wait for writing the cache on both cases
